site_name: Something Stochastic
site_url: https://somethingstochastic.com
site_dir: public
site_author: "Dominik Kiersz"
docs_dir: ./docs
#repo_url: https://github.com/DAKiersz/something-stochastic
#repo_name: DAKiersz/something-stochastic

# https://www.mkdocs.org/user-guide/configuration/
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  custom_dir: overrides
  language: en
  palette:
    - scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark Mode

    - scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Light Mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/img/stochastic-logo-banner.png
  # custom parameter via overrides
  title:
    show_site_name: false

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist

plugins:
  - tags:
      enabled: false
  - search
  - roamlinks
  - blog:
      blog_dir: Blog
      archive: true

extra:
  generator: false
extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js