image: python:3.11.3-slim-bullseye

pages:
  stage: build
  script:
    - pip install -r requirements.txt
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  only:
    - main
