name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Job - Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.11'

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build MkDocs site
      run: |
        mkdocs build --strict --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: something-stochastic-build
        path: public
      continue-on-error: false

  deploy:
    name: Job - Deploy
    runs-on: ubuntu-latest
    needs: build
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: something-stochastic-build
        path: ${{ github.repository }}/public

    - name: Deploy - Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: "upload"
        app_location: "${{ github.repository }}/public"
        output_location: ""
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        skip_app_build: true